POST http://localhost:8000/
content-type: application/json

{
  "question": "What is Engineering Economics and Management?", 
  "answer": "Engineering Economics and Management focuses on interpreting technology led wealth creation dynamics as reoccurring patterns for scaling up invention & innovation art of economic value creation out of ideas with science, engineering and management practices—for endlessly expanding reservoir of wealth from scarce resources."
}

###

POST http://localhost:8000/insert
content-type: application/json

{
  "files": "ch1.pdf,Climate_change_impact_and_disaster_vulne.pdf"
}